package uabc.ic.benjaminbolanos.practica6;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author bbola
 */
public class MainFrame extends javax.swing.JFrame {

    private final Control control;
    private int sliderAnterior;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        control = new Control();
        control.simular(checkBoxes());
        sliderAnterior = slider.getValue();
        graficaLabel.setIcon(new ImageIcon("src/main/resources/imagenes/grafica.png"));
        simularQS();
    }
    
    private void simularQS(){
        int[] arr = new int[100*5*5*5*5*5];
        Algoritmos al = new Algoritmos();
        Random r = new Random();
        for(int i = 0; i < arr.length; i++){
            arr[i] = r.nextInt(100);
        }
        long inicio = System.nanoTime();
        al.quicksortNS(arr);
        long fin = System.nanoTime();
        System.out.println("Test: " + (fin-inicio));
    }
    
    private boolean[] checkBoxes(){
        return new boolean[]{
            insercionCb.isSelected(), quicksortCb.isSelected(),
            seleccionCb.isSelected(), shellCb.isSelected(), 
            bucketsortCb.isSelected(), radixsortCb.isSelected(), 
            sortCb.isSelected()};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        graficaLabel = new javax.swing.JLabel();
        radixsortCb = new javax.swing.JCheckBox();
        quicksortCb = new javax.swing.JCheckBox();
        insercionCb = new javax.swing.JCheckBox();
        seleccionCb = new javax.swing.JCheckBox();
        shellCb = new javax.swing.JCheckBox();
        sortCb = new javax.swing.JCheckBox();
        bucketsortCb = new javax.swing.JCheckBox();
        slider = new javax.swing.JSlider();
        sliderLabel = new javax.swing.JLabel();
        actualizarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica 6");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        mainPanel.setBackground(new java.awt.Color(46, 48, 50));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(graficaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        radixsortCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        radixsortCb.setForeground(new java.awt.Color(255, 255, 255));
        radixsortCb.setSelected(true);
        radixsortCb.setText("Radixsort");
        radixsortCb.setIconTextGap(5);
        mainPanel.add(radixsortCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        quicksortCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        quicksortCb.setForeground(new java.awt.Color(255, 255, 255));
        quicksortCb.setSelected(true);
        quicksortCb.setText("Quicksort");
        quicksortCb.setIconTextGap(5);
        mainPanel.add(quicksortCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        insercionCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        insercionCb.setForeground(new java.awt.Color(255, 255, 255));
        insercionCb.setSelected(true);
        insercionCb.setText("Insercion");
        insercionCb.setIconTextGap(5);
        mainPanel.add(insercionCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        seleccionCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        seleccionCb.setForeground(new java.awt.Color(255, 255, 255));
        seleccionCb.setSelected(true);
        seleccionCb.setText("Seleccion");
        seleccionCb.setIconTextGap(5);
        mainPanel.add(seleccionCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        shellCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        shellCb.setForeground(new java.awt.Color(255, 255, 255));
        shellCb.setSelected(true);
        shellCb.setText("Shell");
        shellCb.setIconTextGap(5);
        mainPanel.add(shellCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        sortCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        sortCb.setForeground(new java.awt.Color(255, 255, 255));
        sortCb.setSelected(true);
        sortCb.setText("Sort");
        sortCb.setIconTextGap(5);
        mainPanel.add(sortCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        bucketsortCb.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bucketsortCb.setForeground(new java.awt.Color(255, 255, 255));
        bucketsortCb.setSelected(true);
        bucketsortCb.setText("Bucketsort");
        bucketsortCb.setIconTextGap(5);
        mainPanel.add(bucketsortCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        slider.setMaximum(6);
        slider.setMinimum(1);
        slider.setValue(3);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        mainPanel.add(slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        sliderLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        sliderLabel.setForeground(new java.awt.Color(255, 255, 255));
        sliderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sliderLabel.setText("Arreglos por Algoritmos: 3");
        mainPanel.add(sliderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 200, 30));

        actualizarButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        actualizarButton.setForeground(new java.awt.Color(255, 255, 255));
        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });
        mainPanel.add(actualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 120, 40));

        jPanel1.setBackground(new java.awt.Color(255, 249, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        sliderLabel.setText("Arreglos por Algoritmo: " + slider.getValue());
        control.setArreglosPorAlgoritmos(slider.getValue());
    }//GEN-LAST:event_sliderStateChanged

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        if(sliderAnterior == slider.getValue()){
            control.graficar(checkBoxes());
        } else {
            control.simular(checkBoxes());
            sliderAnterior = slider.getValue();
        }
        ImageIcon icon = new ImageIcon("src/main/resources/imagenes/grafica.png");
        icon.getImage().flush();
        graficaLabel.setIcon(icon);
        graficaLabel.revalidate();
        graficaLabel.repaint();
    }//GEN-LAST:event_actualizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatDarculaLaf() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JCheckBox bucketsortCb;
    private javax.swing.JLabel graficaLabel;
    private javax.swing.JCheckBox insercionCb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox quicksortCb;
    private javax.swing.JCheckBox radixsortCb;
    private javax.swing.JCheckBox seleccionCb;
    private javax.swing.JCheckBox shellCb;
    private javax.swing.JSlider slider;
    private javax.swing.JLabel sliderLabel;
    private javax.swing.JCheckBox sortCb;
    // End of variables declaration//GEN-END:variables
}
